project:
  type: website
  preview:
    port: 7777
    browser: false

website:
  title: Zack Batist
  site-url: https://zackbatist.info
  description: "Postdoctoral Researcher at McGill University"
  favicon: assets/favicon.ico
  page-navigation: false
  back-to-top-navigation: false

  navbar:
    tools:
    - icon: github
      href: https://www.github.com/zackbatist
    right:
      - href: publications.qmd
      # - href: projects.qmd
      - href: cv.pdf
        text: CV
        target: _blank
      - href: posts.qmd


  page-footer:  
    left: Made with [Quarto](https://quarto.org)
    center: |
      <a class="link me-1" href="https://github.com/zackbatist" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link me-1" href="https://orcid.org/0000-0003-1072-5198" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link me-1" href="https://archaeo.social/@zackbatist" title="Mastodon" target="_blank"rel="noopener">{{< fa brands mastodon >}}</a>
      <a class="link me-1" href="https://zackbatist.info/blog/index.xml" title="rss" target="_blank" rel="noopener">{{< fa rss-square >}}</a>

format: 
  html:
    theme: darkly
    code-link: true
    lightbox: true
    

