project:
  type: website
  preview:
    port: 7777
    browser: false

website:
  title: Zack Batist
  # description: Postdoctoral Researcher at McGill University
  site-url: https://zackbatist.info
  repo-url: https://github.com/zackbatist/zackbatist.github.io
  repo-actions: none
  bread-crumbs: true
  page-navigation: false
  back-to-top-navigation: false
  favicon: assets/favicon.ico
  page-footer:
    right: |
      This page built with ❤️ and <a href="https://quarto.org/" target="_blank" rel="noopener">Quarto</a> | <a class="link me-1" href="https://creativecommons.org/publicdomain/zero/1.0/" target="_blank" rel="noopener">CC0</a>
    center: |
      <a class="link me-1" href="https://github.com/zackbatist" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link me-1" href="https://orcid.org/0000-0003-1072-5198" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link me-1" href="https://archaeo.social/@zackbatist" title="Mastodon" target="_blank"rel="noopener">{{< fa brands mastodon >}}</a>
      <a class="link me-1" href="https://zackbatist.info/blog/index.xml" title="rss" target="_blank" rel="noopener">{{< fa rss-square >}}</a>
  navbar:
    tools:
    - icon: github
      href: https://www.github.com/zackbatist
    right:
      - href: publications.qmd
      - href: projects.qmd
      - href: posts.qmd
      - href: cv.pdf
        text: CV
        target: _blank
      
  sidebar: 
    logo: "assets/picture.png"
    pinned: true
    align: center
    style: docked
    search: true
    collapse-level: 2
    contents:
      - publications.qmd
      - projects.qmd
      # - notes.qmd
      - posts.qmd
format:
  html:
    theme: cosmo
    page-layout: full
    code-copy: true
    code-link: true
    code-overflow: wrap
    toc: true
    lightbox: true
    grid:
      sidebar-width: 150px
filters:
  - include-files.lua
  - quarto
execute:
  freeze: auto

