baseURL: "https://zackbatist.info/"
title: Zack Batist
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: publications
          weight: 1
        - name: CV
          url: cv.pdf
          weight: 2
#        - name: Blog
#          url: https://blog.zackbatist.info/
#          weight: 3
#        - name: GitHub
#          url: https://github.com/zackbatist
#          weight: 4
#        - name: Mastodon
#          url: https://archaeo.social/@zackbatist
#          weight: 5


params:
    description: "Postdoctoral Researcher at McGill University"
    author: Zack Batist
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Zack Batist
          subtitle: "Postdoctoral Researcher at McGill University"
          imageUrl: "picture.png"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications
            - name: CV
              url: cv.pdf
            - name: Blog
              url: https://blog.zackbatist.info/
            - name: GitHub
              url: https://github.com/zackbatist
            - name: Mastodon
              url: https://archaeo.social/@zackbatist
#            - name: ORCID
#              url: https://orcid.org/0000-0003-0435-508X

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Zack Batist"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2